### ISSUE TITLE
cannot create children while terminating or terminated

### ISSUE THREAD

**Issue by fkumro** [maiha/http-mock#20]
Hi,

I am attempting to use `http-mock` in my unit tests but the error below is being thrown. I'm using Scala 2.11.11 and Scalatest 3.0.4. Wondering if the Akka system is being shut down somehow? Any thoughts/help would be appreciated!

The application I am testing does not make use of an actor system.

I've used two different ways to construct the mock HTTP server, both with the same result.

```scala
HttpMock.run(9000) { httpServer => ... }
```

as a fixture

```scala
def withHttpMock(testCode: HttpMock => Any) {
    val httpServer = HttpMock.start()
    try {
      testCode(httpServer)
    } finally httpServer.stop()
  }
```

Error:

```scala
[info]   java.lang.IllegalStateException: cannot create children while terminating or terminated
[info]   at akka.actor.dungeon.Children$class.makeChild(Children.scala:270)
[info]   at akka.actor.dungeon.Children$class.attachChild(Children.scala:48)
[info]   at akka.actor.ActorCell.attachChild(ActorCell.scala:370)
[info]   at akka.stream.impl.ExtendedActorMaterializer.actorOf(ActorMaterializerImpl.scala:60)
[info]   at akka.stream.impl.GraphStageIsland.onIslandReady(PhasedFusingActorMaterializer.scala:742)
[info]   at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:507)
[info]   at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:420)
[info]   at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
[info]   at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:496)
[info]   at akka.stream.scaladsl.Source.runWith(Source.scala:83)
```

**Comment by fkumro** [comment]
Using `AsyncFlatSpec` instead of `FlatSpec` solved my issue.
